MatchMaker/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from apps.builder import urls as builder_urls
from apps.flatpage.views import HomeView
js_info_dict = {
    'packages': ('django.conf',),
}

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    # Examples:

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^events/', include('apps.events.urls')),

    url(r'^reports/', include('apps.reports.urls')),
    url(r'^api/v1/', include('apps.rfidAPI.urls')),


    url(r'^', include('apps.company.urls')),

    url(r'^', include('apps.survey.urls')),

    url(r'^', include('apps.users.urls')),
    url(r'^', include('apps.search.urls')),
    url(r'^', include('apps.match.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^select2/', include('select2.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^', include('apps.userrole.urls')),
    url(r'^', include('apps.communication.urls')),
    url(r'^', include('apps.event_registration.urls')),

    url(r'^api/rfid/', include('apps.rfid.urls')),
    url(r"^login/user/(?P<user_id>.+)/$", "loginas.views.user_login", name="loginas-user-login"),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^jsi18n$', 'django.views.i18n.javascript_catalog', js_info_dict),


)

from MatchMaker.api_tastypie_urls import api as tastypie_api
urlpatterns += patterns('',
    (r'^apiv2/',include(tastypie_api.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}
        ),
        #media
        url(
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        )
    )

apps/events/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.views.generic import TemplateView

from . import views
from apps.users.decorators import profile_complete_required

urlpatterns = patterns(
    '',
    url(
        r'^$',
        profile_complete_required(views.EventListView.as_view()),
        name='events'
    ),
    url(
        r'^create/',
        profile_complete_required(views.CreateEventView.as_view()),
        name='create_event'
    ),
    url(
        r'^(?P<pk>\d+)/$',
        profile_complete_required(views.EventDetailsView.as_view()),
        name='event_details'
    ),
    url(
        r'^(?P<pk>\d+)/edit/$',
        profile_complete_required(views.EditEventView.as_view()),
        name='edit_event'
    ),
    url(
        r'^(?P<pk>\d+)/delete/$',
        profile_complete_required(views.DeleteEventView.as_view()),
        name='delete_event'
    ),
    url(
        r'^(?P<event_pk>\d+)/activities/$',
        profile_complete_required(views.ActivitiesListView.as_view()),
        name='activities'
    ),
    url(
        r'^(?P<event_pk>\d+)/create-activity/ajax/$',
        views.AjaxNewActivityView.as_view(),
        name='ajax_new_activity'
    ),
    url(
        r'^update-activity/ajax/(?P<pk>\d+)/$',
        views.AjaxUpdateActivityView.as_view(),
        name='ajax_update_activity'
    ),
    url(
        r'^event-matches/$', 
        TemplateView.as_view(template_name='events/one_one_event_matches.html'), 
        name='event_matches'
    ),
    url(
        r'^event-matches-many/$', 
        TemplateView.as_view(template_name='events/one_many_event_matches.html'), 
        name='event_matches_many'
    ),
    url(
        r'^buyer-match-schedule/$', 
        TemplateView.as_view(template_name='events/buyer_matchmaker_schedule.html'), 
        name='buyer_matchmaker_schedule'
    ),
    url(
        r'^seller-match-schedule/$', 
        TemplateView.as_view(template_name='events/seller_matchmaker_schedule.html'), 
        name='seller_matchmaker_schedule'
    ),
    url(
        r'^event-communication/$', 
        TemplateView.as_view(template_name='events/communication.html'), 
        name='event_communication'
    ),
    url(
        r'^create-activity/$',
        profile_complete_required(views.NewActivity.as_view()),
        name='new_activity'
    ),
    url(r'^activities/(?P<id>\d+)/$', 'apps.events.views.EditActivity', 
        name='activity_edit'),
    url(r'^activities-list/$', 'apps.events.views.ActivitiesList', 
        name='activities_list'),
    url(r'^register-activity/(?P<id>\d+)/$', 'apps.events.views.RegisterActivity', 
        name='register_activity'),
    url(r'^delete-activity/(?P<id>\d+)/$', 'apps.events.views.DeleteActivity', 
        name='delete_activity'),
    url(r'^edit-activity/(?P<id>\d+)/$', 'apps.events.views.EditActivity', 
        name='edit_activity'),
    url(r'^activities-reports/$', 'apps.events.views.ActivitiesReports', 
        name='activities-reports'),
    url(r'^search/$', 'apps.events.views.Search', name='apps.events_search'),
    #url(r'^dashboard/$', 'apps.events.views.dashboard', name='apps.dashboard'),
    url(r'^upcoming/$', 'apps.events.views.upcoming_events', 
        name='apps.events_upcoming_events'),
	url(r'^past/$', 'apps.events.views.past_events', 
        name='apps.events_past_events'),
	url(r'^review/$', 'apps.events.views.needs_review', 
        name='apps.events_needs_review'),
	url(r'^message/$', 'apps.events.views.event_message', 
        name='apps.events_event_message'),
	url(r'^newuser/$', 'apps.events.views.new_user_email_signup', 
        name='apps.events_new_user_email_signup'),
    url(r'^emailpreferences/(?P<username>[\w\d\-\.@+_]+)/$', 'apps.events.views.email_preferences', 
        name='apps.events_email_preferences'),
	# url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/edit/$', 'apps.events.views.edit_event',
     #    name='apps.events_edit_event'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/yes/newuser/$', 'apps.events.views.rsvp_new_user', 
        name='apps.events_rsvp_new_user'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/no/$', 'apps.events.views.rsvp_cancel', 
        name='apps.events_rsvp_cancel'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/yes/$', 'apps.events.views.rsvp_event', 
        name='apps.events_rsvp_event'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/endorse/$', 'apps.events.views.endorse', 
        name='apps.events_event_endorse'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/publish/$', 'apps.events.views.event_publish', 
        name='apps.events_event_publish'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/approve/$', 'apps.events.views.event_approve', 
        name='apps.events_event_approve'),
    # url(r'^event/(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/$', 'apps.events.views.view_event',
    #     name='apps.events_view_event'),
    # url(r'^event/(?P<event_id>\d+)/$', 'apps.events.views.view_event',
    #     name='apps.events_view_event'),
    url(r'^attend/$', 'apps.events.views.rsvp_event', name='apps.events_rsvp'),
    url(r'^attending/(?P<id>\d+)/$', 'apps.events.views.Register', 
        name='apps.events_register'),
    url(
        regex=r'activitytype/create/$',
        view=views.ActivityTypeCreateView.as_view(),
        name='activity_type_create'
    ),
    url(
        regex=r'activitytype/list/$',
        view=views.ActivityTypeListView.as_view(),
        name='activity_type_list'
    ),
    url(
        regex=r'manage/role/$',
        view=views.ManageRoleView.as_view(),
        name='manage_role_list'
    ),
    url(
        r'^search/facility/',
        views.SearchFacilityView.as_view(),
        name='search-facility'
    ),
    url(
        r'^facility/(?P<pk>\d+)/(?P<looking_date>\d{4}-\d{2}-\d{2})/$',
        views.FacilityAvailableTimeView.as_view(),
        name='facility-available'
    )
)

# Rebuilt views requires to delete
urlpatterns += patterns(
    '',
    url(
        r'^create-activity-old/$',
        'apps.events.views.OldNewActivity',
        name='new_activity_old'
    ),
)

apps/match/models.py
from django.db import models
from apps.users.models import User
from apps.events.models import Activity
import pickle
from django.core.files.base import ContentFile

class Schedule(models.Model):
    creator = models.ForeignKey(User)
    activity = models.ForeignKey(Activity)
    name = models.CharField(max_length=255,blank=True,null=True,verbose_name='Name of Schedule')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    schedule_data = models.FileField(upload_to='schedules/',blank=True,null=True)

    def get_data(self):
        f = self.schedule_data
        f.open(mode="rb")
        data = pickle.load(f)
        f.close()
        return data        

    def put_data(self, data):
        content = pickle.dumps(data)
        filename = str(self.id) + ".pickle"
        self.schedule_data.save(filename, ContentFile(content))        

    def update_data(self,data):
        fname = self.schedule_data.file.name
        f = open(fname, "wb")
        pickle.dump(data,f)
        f.close()

    def __unicode__(self):
        return self.name

class Session(models.Model):
    schedule = models.ForeignKey(Schedule)
    seller = models.CharField(max_length=255,blank=True,null=True)
    buyer  = models.CharField(max_length=255,blank=True,null=True)
    start  = models.CharField(max_length=255,blank=True,null=True)
    end   =models.CharField(max_length=255,blank=True,null=True)

    def __unicode__(self):
        return self.seller+':'+self.buyer

class Rank(models.Model):
    calculated_at = models.DateTimeField(auto_now=True)
    rank = models.FileField(upload_to='ranks/',blank=True,null=True)

apps/events/templates/gather_event_create.html
{% extends "content-base.html" %}
{% load static %}

{% block content %}

{% if messages %}
<div class="messages">
	{% for message in messages %}
	<div class="alert alert-info">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
	</div>
	{% endfor %}
</div>
{% endif %}


<div id="event-preamble">
	{% if not is_event_admin %}
		{% include 'snippets/event_hosting_info.html' %}
	{% else %}
		{% include 'snippets/event_admin_info.html' %}
	{% endif %}
</div>

<div class="col-md-8">

	<form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% url gather_create_event location.slug %}">{% csrf_token %}
		{% include "snippets/event_form_body.html" %}
		<input id="submit-event" type="submit" class="btn btn-lg" value="Submit Event">
	</form>
</div>
<div class="col-md-4">
</div>

{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="/media/js/jquery-ui-timepicker-addon.js"></script>
<script>

	{% include "snippets/js/organizers_autocomplete.js" %}

	$('#id_start').datetimepicker({
		controlType: 'select'
	});	
	$('#id_end').datetimepicker({
		controlType: 'select'
	});

	clean_slug_value = function(e) {
		// make sure there's only letters, numbers and hyphens by removing
		// special characters, and replace spaces with hyphens (making sure
		// only one hyphen in a row). force the slug to lowercase. 
		str = $(e.data.elem_id).val();
		slugified = str.replace(/[^\d\w\- ]/g, "").replace(/ /g,"-").replace(/-{2,}/, "-").toLowerCase();

		// check max length
		if (slugified.length > 50) {
			slugified = slugified.substring(0,50);
		}
		// make sure there's no trailing hyphens (after trimming, because that
		// will change the last character)
		slugified = slugified.replace(/-$/, "");
		$("#id_slug").val(slugified);
		return false;
	};

	$("#id_title").on('input', {'elem_id': "#id_title"}, clean_slug_value);
	$("#id_slug").focusout({'elem_id': "#id_slug"}, clean_slug_value)


</script>
{% endblock %}

apps/events/templates/gather_event_edit.html
{% extends "content-base.html" %}
{% load static %}

{% block content %}

<form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% url gather_edit_event location.slug event_id event_slug %}">{% csrf_token %}
	{% include "snippets/event_form_body.html" %}
	<input id="submit-event" type="submit" class="btn" value="Submit">
</form>

{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="/media/js/jquery-ui-timepicker-addon.js"></script>
<script>

	{% include "snippets/js/organizers_autocomplete.js" %}

	$('#id_start').datetimepicker({
		controlType: 'select'
	});	
	$('#id_end').datetimepicker({
		controlType: 'select'
	});

	clean_slug_value = function(e) {
		// make sure there's only letters, numbers and hyphens by removing
		// special characters, and replace spaces with hyphens (making sure
		// only one hyphen in a row). force the slug to lowercase. 
		str = $(e.data.elem_id).val();
		slugified = str.replace(/[^\d\w\- ]/g, "").replace(/ /g,"-").replace(/-{2,}/, "-").toLowerCase();

		// check max length
		if (slugified.length > 50) {
			slugified = slugified.substring(0,50);
		}
		// make sure there's no trailing hyphens (after trimming, because that
		// will change the last character)
		slugified = slugified.replace(/-$/, "");
		$("#id_slug").val(slugified);
		return false;
	};

	$("#id_title").on('input', {'elem_id': "#id_title"}, clean_slug_value);
	$("#id_slug").focusout({'elem_id': "#id_slug"}, clean_slug_value)


</script>
{% endblock %}

apps/events/templates/gather_event_guide.html
{% extends "content-base.html" %}
{% block content %}

<h1>Event Hosting Guide</h1>

<h2 class="event-guide-title">Community Events</h2>
<div>
	We love to host creative and interesting events that are open to and enrich our community. Example of common and past events:
	<ul>
		<li>Meetups
		<li>Dinners
		<li>Hackathons
		<li>Speakers
		<li>Salons
		<li>Tastings
		<li>Workshops
		<li>Movie nights
		<li>Concerts
	</ul>

	Available for your event:
	<ul>
		<li>Giant freestanding screen (~4’ x 6’) and a projector
		<li>Dining room which can seat 20-30 easily
		<li>Living room can hold about 40, 50-60 with standing-room-only
		<li>Baby grand piano for performances
		<li>Kitchen for preparing food/snacks. We usually have some room to squeeze items that need refrigeration but not a ton. 
		<li>Downstairs movie area, seats 5-8 (movies can be shown on the big screen as well)
		<li>Serving platters, dishes and cutlery for about 60, wine glasses for about 40 (depending on where we are in the cycle of them breaking and being replaced) 
		<li>Speakers - we have one set of speakers that's often floating around the house either in the living room or on the lower level by the movie area. 
		<li>Lots of folding chairs - usually tucked away in a corner of the dining room or by the bottom of the main staircase on the ground floor. Some additional chairs also in the coworking area. 
		<li>Furniture - feel free to rearrange in particular the living and dining rooms as appropriate for your event; just put things back when you're done. 

	</ul>


	<h3>Hosting process</h3>
	<ul>
		<li><b>You are responsible for set up and spotless clean-up after.</b>
		<ul>
			<li>Putting back furniture
			<li>Washing and putting away all dishes from the event
			<li>Spot check for things left out or around. 
		</ul>
		<li>Supplies: You bring your own supplies of food and drink. You are welcome to use our dishes and plates. We have tons. 
		<li>Introduce yourself to people in the house. We have many residents and guests who are likely to attend and/or be around during setup or the event itself. 
		<li>Advertising: you are the host and so it’s up to you to decide how you want to promote the events. Many people use eventbrite.com or Facebook to track RSVPs and communicate with guests. If you would like us to advertise your event on our events list, Facebook or Twitter, we’d be very happy to. Please provide:
		<ul>
			<li>Date and time
			<li>Event description
			<li>An email announcement we can forward to our list
			<li>A Facebook post we can share
			<li>A Tweet we can retweet
		</ul>
	</ul>

	<h3>Pricing</h3>
		<ul>
			<li>Small free community events are free to host. 
			<li>If you are hosting a non-for-profit event but charging for tickets to cover costs, we ask for a $50 contribution to the house. This goes towards our costs of maintaining the space - we have cleaners regularly, extra garbage pickup to support events, and general upkeep/maintenance of furniture, glassware, electronics, and general tricked-out-ness to support awesome activities!
			<li>For-profit events are also welcome, but we ask for an appropriate revenue-share based on your event model.  
		</ul>
</div>

<h2 class="event-guide-title">Private Events</h2>
<div>
	We are also open to hosting private events if they advance a specific goal
	or aim in line with our community, or makes a meaningful financial
	contribution to house - which in turn goes towards supporting more open
	community events. Example:
	<ul>
		<li>Fundraisers
		<li>Special Company dinners
		<li>Courses
		<li>Wedding Showers
		<li>Small conferences and offsites
	</ul>
	Please contact us directly at <a href="mailto:events@embassynetwork.com">events@embassynetwork.com</a> to discuss your private event ideas! 
</div>

{% endblock %}

apps/events/templates/gather_event_view.html
{% extends "content-base.html" %}
{% block content %}

<meta property="og:image" content="https://{{domain}}{{ MEDIA_URL }}{{ event.image }}"/>
<meta property="og:title" content="{{event.title|title}}"/>
<meta property="og:url" content="https://{{domain}}/events/{{event.id}}/{{event.slug}}"/>
<meta property="og:description" content="{{event.description}}"/>

<div id="event-view-wrapper">
	<div class="modal fade" id="new-user-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-med">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title">Almost There...</h3>
			</div>
			<div class="modal-body">
				<h4>We need a bit more info to keep you posted on this event. </h4> 	
				<p><em>Already a member? <a href="{% url django.contrib.auth.views.login %}">Login instead</a></em></p>
				<div id="new-user-form-errors"></div>
				<form id="new-user-form" class="form-horizontal">
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.first_name.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.first_name }}
						{{ new_user_form.first_name.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.last_name.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.last_name }}
						{{ new_user_form.last_name.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.username.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.username }}
						{{ new_user_form.username.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.email.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.email }}
						{{ new_user_form.email.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.password1.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.password1 }}
						{{ new_user_form.password1.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.password2.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.password2 }}
						{{ new_user_form.password2.errors }}
						</span>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
							<div class="checkbox">
								<label for="email-notifications">
									<input id="id_email_notifications" type="checkbox" name="email-notifications" false> Sign up for weekly event emails?
								</label>
							</div>
							<div class="text-muted">We won't send you any other emails unless you ask for them!</div>
						</div>
					</div>
					<input class="btn btn-default" type="submit" value="Submit RSVP">
				</form>
			</div>
		</div>
	</div>
	</div>


	{% if messages %}
	<div class="messages">
		{% for message in messages %}
		<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert">×</button>
			<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</div>
		</div>
		{% endfor %}
</div>
	{% endif %}

	{% comment %} this area has an if statement and only displays if the event is not live {% endcomment %}
	<div id="event-status-area">
		{% include 'snippets/event_status_area.html' %}
	</div>

	{% if event.status == 'live' and event.private %}
		<div class="text-danger event-status">
			<span class="glyphicon glyphicon-star"></span> This event is viewable to those with the link.
		</div>
	{% endif %}


	<h1 class="event-detail-title">{{ event.title|title }}</h1> 
	{% if user_is_organizer %}
		<a id="event-edit-link" class="thirtypx-spacer-left" href="edit/">edit</a>
	{% endif %}
	<div class="event-time"> 
	{% with event.start|date as start_date %}
	{% with event.end|date as end_date %}
		<span class="event-date-day pull-left"> {{ event.start|date:'D'}}</span>
		<span class="event-date-month pull-left">{{ event.start|date:'b'|title}}</span>
		<span class="event-date-day pull-left"> {{ event.start|date:'j'}}</span>
		<span class="event-date-time pull-left">{{ event.start|date:'f A'}}</span>
		<span class="event-date-separator pull-left"><em>until</em></span>
		{% if start_date != end_date %}
		<span class="event-date-day pull-left"> {{ event.end|date:'D'}}</span>
		<span class="event-date-month pull-left">{{ event.end|date:'b'|title}}</span>
		<span class="event-date-day pull-left"> {{ event.end|date:'j'}}</span>
		{% endif %}
		<span class="event-date-time pull-left">{{ event.end|date:'f A'}}</span>
		<span class="event-location">, {{event.location }}</span>
	{% endwith %}
	{% endwith %}
	</div>

	<div class="col-md-8">
		<div class="row"> <img class="event-detail-img img-rounded" src="{{ MEDIA_URL }}{{ event.image }}" /></div>

		{% with event.organizers.get_query_set as organizers %}
		<h3>Organized by 
			{% for o in organizers %}
			<a href="{% url user_detail o.username %}">{{ o.first_name }} {{o.last_name}}</a>{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</h3>
		{% endwith %}
		{{ event.description|safe|linebreaks }}
	</div>

	<div class="col-md-4" id="rsvp-info">
		{% include 'snippets/rsvp_info.html' %}
	</div>

	{% if user_is_organizer %}
	<div class="col-md-12" id="organizer-notes">
		<hr>
		<h4>Organizer Notes</h4>
		<p>{{event.orgnanizer_notes|default:"No notes"}}</p>
	</div>
	{% endif %}

</div>

{% if event.status == 'live' and not event.private %}
<div class="row">
<div class="col-md-2 col-md-offset-5" id="facebook-share-link">
	<a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2F{{domain}}/events/{{event.id}}/{{event.slug}}" target="_blank"> Share on Facebook </a>
</div>
</div>
{% endif %}

{% endblock %}

{% block extrajs %}
<script>

	$("#new-user-form").submit(function(event) {
		form_data = $("#new-user-form").serialize();
		form_data = form_data + '&csrfmiddlewaretoken=' + '{{ csrf_token }}';
		request = $.ajax({ 
			data: form_data,	
			type: "POST",
			url: '{% url gather_rsvp_new_user location.slug event.id event.slug %}'
		});

		request.done(function(msg) {
			if (msg.length > 0) {
				data = JSON.parse(JSON.parse(msg));
				if (data.errors) {
					console.log("errors");
					errors = data.errors;
					error_html = "<div class='text-danger'>There were errors in the form:</div>";
					for (var k in errors) {
						error_html += '<div class="text-danger">' + k + ': ' + errors[k] + '</div>';
					}
					console.log(error_html);
					$("#new-user-form-errors").html(error_html);
				} else {
					console.log("shouldn't be here...");
				} 
			} else {
				console.log("success");
				location.reload();
			}
		});

		request.fail(function(msg) {
			$("#attendance-message").html('<span class="bg-danger">Oops, there was a problem. Please try again.</span>')
		});

		event.preventDefault();
	});

	$("#approve-for-publication").click(function() {
		request = $.ajax({ 
			data: {
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			},	
			type: "POST",
			url: '{% url gather_event_approve location.slug event.id event.slug %}'
		});
		request.done(function(msg) {
			$("#event-status-area").html(msg);
		});

		request.fail(function(msg) {
			$("#event-status-area").html('<span class="text-danger">Oops, there was a problem. Please try again.</span>')
		});

		event.preventDefault();
	});

	$("#publish-event").click(function() {
		request = $.ajax({ 
			data: {
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			},	
			type: "POST",
			url: '{% url gather_event_publish location.slug event.id event.slug %}',
		});

	});

</script>
{% endblock %}

apps/events/templates/gather_events_admin_needing_review.html
{% extends "content-base.html" %}
{% block content %}

<div class="text-danger" id="event-admin-heads-up"><span class="glyphicon glyphicon-exclamation-sign"></span> Only events in the future are shown here</div>

<ul class="nav nav-tabs" id="event-list-tabs">
	<li class="active"><a href="#pending" data-toggle="tab">Waiting Approval</a></li>
	<li><a href="#feedback" data-toggle="tab">Seeking Feedback</a></li>
</ul>

<div class="tab-content">

	<div id="pending" class="tab-pane active fade in">
		{% for event in events_pending %}
			{% include 'snippets/event-list-compact.html' %}
		{% endfor %}
	</div>
	<div id="feedback" class="tab-pane fade">
		{% for event in events_under_discussion %}
			{% include 'snippets/event-list-compact.html' %}
		{% endfor %}
	</div>

</div>


{% endblock %}