MatchMaker/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from apps.builder import urls as builder_urls
from apps.flatpage.views import HomeView
js_info_dict = {
    'packages': ('django.conf',),
}

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    # Examples:

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^events/', include('apps.events.urls')),

    url(r'^reports/', include('apps.reports.urls')),
    url(r'^api/v1/', include('apps.rfidAPI.urls')),


    url(r'^', include('apps.company.urls')),

    url(r'^', include('apps.survey.urls')),

    url(r'^', include('apps.users.urls')),
    url(r'^', include('apps.search.urls')),
    url(r'^', include('apps.match.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^select2/', include('select2.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^', include('apps.userrole.urls')),
    url(r'^', include('apps.communication.urls')),
    url(r'^', include('apps.event_registration.urls')),

    url(r'^api/rfid/', include('apps.rfid.urls')),
    url(r"^login/user/(?P<user_id>.+)/$", "loginas.views.user_login", name="loginas-user-login"),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^jsi18n$', 'django.views.i18n.javascript_catalog', js_info_dict),


)

from MatchMaker.api_tastypie_urls import api as tastypie_api
urlpatterns += patterns('',
    (r'^apiv2/',include(tastypie_api.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}
        ),
        #media
        url(
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        )
    )

apps/events/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.views.generic import TemplateView

from . import views
from apps.users.decorators import profile_complete_required

urlpatterns = patterns(
    '',
    url(
        r'^$',
        profile_complete_required(views.EventListView.as_view()),
        name='events'
    ),
    url(
        r'^create/',
        profile_complete_required(views.CreateEventView.as_view()),
        name='create_event'
    ),
    url(
        r'^(?P<pk>\d+)/$',
        profile_complete_required(views.EventDetailsView.as_view()),
        name='event_details'
    ),
    url(
        r'^(?P<pk>\d+)/edit/$',
        profile_complete_required(views.EditEventView.as_view()),
        name='edit_event'
    ),
    url(
        r'^(?P<pk>\d+)/delete/$',
        profile_complete_required(views.DeleteEventView.as_view()),
        name='delete_event'
    ),
    url(
        r'^(?P<event_pk>\d+)/activities/$',
        profile_complete_required(views.ActivitiesListView.as_view()),
        name='activities'
    ),
    url(
        r'^(?P<event_pk>\d+)/create-activity/ajax/$',
        views.AjaxNewActivityView.as_view(),
        name='ajax_new_activity'
    ),
    url(
        r'^update-activity/ajax/(?P<pk>\d+)/$',
        views.AjaxUpdateActivityView.as_view(),
        name='ajax_update_activity'
    ),
    url(
        r'^event-matches/$', 
        TemplateView.as_view(template_name='events/one_one_event_matches.html'), 
        name='event_matches'
    ),
    url(
        r'^event-matches-many/$', 
        TemplateView.as_view(template_name='events/one_many_event_matches.html'), 
        name='event_matches_many'
    ),
    url(
        r'^buyer-match-schedule/$', 
        TemplateView.as_view(template_name='events/buyer_matchmaker_schedule.html'), 
        name='buyer_matchmaker_schedule'
    ),
    url(
        r'^seller-match-schedule/$', 
        TemplateView.as_view(template_name='events/seller_matchmaker_schedule.html'), 
        name='seller_matchmaker_schedule'
    ),
    url(
        r'^event-communication/$', 
        TemplateView.as_view(template_name='events/communication.html'), 
        name='event_communication'
    ),
    url(
        r'^create-activity/$',
        profile_complete_required(views.NewActivity.as_view()),
        name='new_activity'
    ),
    url(r'^activities/(?P<id>\d+)/$', 'apps.events.views.EditActivity', 
        name='activity_edit'),
    url(r'^activities-list/$', 'apps.events.views.ActivitiesList', 
        name='activities_list'),
    url(r'^register-activity/(?P<id>\d+)/$', 'apps.events.views.RegisterActivity', 
        name='register_activity'),
    url(r'^delete-activity/(?P<id>\d+)/$', 'apps.events.views.DeleteActivity', 
        name='delete_activity'),
    url(r'^edit-activity/(?P<id>\d+)/$', 'apps.events.views.EditActivity', 
        name='edit_activity'),
    url(r'^activities-reports/$', 'apps.events.views.ActivitiesReports', 
        name='activities-reports'),
    url(r'^search/$', 'apps.events.views.Search', name='apps.events_search'),
    #url(r'^dashboard/$', 'apps.events.views.dashboard', name='apps.dashboard'),
    url(r'^upcoming/$', 'apps.events.views.upcoming_events', 
        name='apps.events_upcoming_events'),
	url(r'^past/$', 'apps.events.views.past_events', 
        name='apps.events_past_events'),
	url(r'^review/$', 'apps.events.views.needs_review', 
        name='apps.events_needs_review'),
	url(r'^message/$', 'apps.events.views.event_message', 
        name='apps.events_event_message'),
	url(r'^newuser/$', 'apps.events.views.new_user_email_signup', 
        name='apps.events_new_user_email_signup'),
    url(r'^emailpreferences/(?P<username>[\w\d\-\.@+_]+)/$', 'apps.events.views.email_preferences', 
        name='apps.events_email_preferences'),
	# url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/edit/$', 'apps.events.views.edit_event',
     #    name='apps.events_edit_event'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/yes/newuser/$', 'apps.events.views.rsvp_new_user', 
        name='apps.events_rsvp_new_user'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/no/$', 'apps.events.views.rsvp_cancel', 
        name='apps.events_rsvp_cancel'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/yes/$', 'apps.events.views.rsvp_event', 
        name='apps.events_rsvp_event'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/endorse/$', 'apps.events.views.endorse', 
        name='apps.events_event_endorse'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/publish/$', 'apps.events.views.event_publish', 
        name='apps.events_event_publish'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/approve/$', 'apps.events.views.event_approve', 
        name='apps.events_event_approve'),
    # url(r'^event/(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/$', 'apps.events.views.view_event',
    #     name='apps.events_view_event'),
    # url(r'^event/(?P<event_id>\d+)/$', 'apps.events.views.view_event',
    #     name='apps.events_view_event'),
    url(r'^attend/$', 'apps.events.views.rsvp_event', name='apps.events_rsvp'),
    url(r'^attending/(?P<id>\d+)/$', 'apps.events.views.Register', 
        name='apps.events_register'),
    url(
        regex=r'activitytype/create/$',
        view=views.ActivityTypeCreateView.as_view(),
        name='activity_type_create'
    ),
    url(
        regex=r'activitytype/list/$',
        view=views.ActivityTypeListView.as_view(),
        name='activity_type_list'
    ),
    url(
        regex=r'manage/role/$',
        view=views.ManageRoleView.as_view(),
        name='manage_role_list'
    ),
    url(
        r'^search/facility/',
        views.SearchFacilityView.as_view(),
        name='search-facility'
    ),
    url(
        r'^facility/(?P<pk>\d+)/(?P<looking_date>\d{4}-\d{2}-\d{2})/$',
        views.FacilityAvailableTimeView.as_view(),
        name='facility-available'
    )
)

# Rebuilt views requires to delete
urlpatterns += patterns(
    '',
    url(
        r'^create-activity-old/$',
        'apps.events.views.OldNewActivity',
        name='new_activity_old'
    ),
)

apps/search/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',

    url(r'^basic_search/$', 'apps.search.views.basic_search', name='basic_search'),
    url(r'^advanced_search/$', 'apps.search.views.advanced_search', name='advanced_search'),

    )

apps/survey/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^survey/(?P<s_id>\d+)/$', 'apps.survey.views.survey_detail', name='survey_detail'),
    url(r'^confirm/(?P<uuid>\w+)/$', 'apps.survey.views.confirm', name='confirmation'),
    url(r'^privacy/$', 'apps.survey.views.privacy', name='privacy_statement'),
    url(r'^add-question/(?P<s_id>\d+)/$', 'apps.survey.views.create_question', name='dynamic_question_add'),
    url(r'^edit-question/(?P<q_id>\d+)/$', 'apps.survey.views.edit_question', name='dynamic_question_edit'),
    url(r'^delete-survey/(?P<s_id>\d+)/$', 'apps.survey.views.delete_survey', name='delete_survey'),
    url(r'^delete-question/(?P<q_id>\d+)/$', 'apps.survey.views.delete_question', name='delete_question'),
    url(r'^add-survey/$', 'apps.survey.views.create_survey', name='dynamic_field_get'),
    url(r'^edit-survey/(?P<s_id>\d+)/$', 'apps.survey.views.edit_survey', name='survey_edit'),
    url(r'^my-surveys/$', 'apps.survey.views.my_surveys', name='all_surveys'),
    url(r'^view-survey/(?P<s_id>\d+)/$', 'apps.survey.views.view_survey', name='view_survey'),
    url(r'^send-survey/(?P<s_id>\d+)/$', 'apps.survey.views.send_survey', name='send_survey'),




)

apps/search/models.py
from django.db import models
from apps.users.models import User

# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=255, blank=True, null=True, verbose_name='Enter new category name')

    def __unicode__(self):
        return self.name


class Favorites(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    category = models.ForeignKey(Category, max_length=255, blank=True, null=True)
    favorite_results = models.ManyToManyField(User, blank=True, null=True, related_name='user_favorite_results')

    def __unicode__(self):
        return self.user

apps/survey/models.py
from django.db import models
from django.core.exceptions import ValidationError
from apps.users.models import User
from apps.events.models import Event,Activity
from smart_selects.db_fields import ChainedForeignKey


class Survey(models.Model):
    name = models.CharField(max_length=400)
    description = models.TextField(null=True,blank=True)
    creator = models.ForeignKey(User,blank=True,null=True)
    active = models.BooleanField(default=False)
    event = models.ForeignKey(Event,blank=True,null=True,related_name='survey_event')
    activity = ChainedForeignKey(
        Activity,
        chained_field="event",
        chained_model_field="event",
        show_all=False,
        auto_choose=True, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return (self.name)

    def questions(self):
        if self.pk:
            return Question.objects.filter(survey=self.pk)
        else:
            return None

class Category(models.Model):
    name = models.CharField(max_length=400)
    survey = models.ForeignKey(Survey)

    def __unicode__(self):
        return (self.name)

def validate_list(value):
    '''takes a text value and verifies that there is at least one comma '''
    values = value.split(',')
    if len(values) < 2:
        raise ValidationError("The selected field requires an associated list of choices. Choices must contain more than one item.")

class Question(models.Model):
    TEXT = 'text'
    RADIO = 'radio'
    SELECT = 'select'
    SELECT_MULTIPLE = 'select-multiple'
    INTEGER = 'integer'

    QUESTION_TYPES = (
        (TEXT, 'text'),
        (RADIO, 'radio'),
        (SELECT, 'select'),
        (SELECT_MULTIPLE, 'CheckBox'),
        (INTEGER, 'integer'),
    )

    text = models.TextField()
    required = models.BooleanField()
    category = models.ForeignKey(Category, blank=True, null=True,)
    survey = models.ForeignKey(Survey)
    question_type = models.CharField(max_length=200, choices=QUESTION_TYPES, default=TEXT)
    # the choices field is only used if the question type
    choices = models.TextField(blank=True, null=True,
        help_text='if the question type is "radio," "select," or "select multiple" provide a comma-separated list of options for this question .')

    def save(self, *args, **kwargs):
        if (self.question_type == Question.RADIO or self.question_type == Question.SELECT
            or self.question_type == Question.SELECT_MULTIPLE):
            validate_list(self.choices)
        super(Question, self).save(*args, **kwargs)

    def get_choices(self):
        ''' parse the choices field and return a tuple formatted appropriately
        for the 'choices' argument of a form widget.'''
        choices = self.choices.split(',')
        choices_list = []
        for c in choices:
            c = c.strip()
            choices_list.append((c,c))
        choices_tuple = tuple(choices_list)
        return choices_tuple

    def get_single_choice(self):
        ''' parse the choices field and return a tuple formatted appropriately
        for the 'choices' argument of a form widget.'''
        choices = self.choices.split(',')
        choices_list = []
        for c in choices:
            c = c.strip()
            choices_list.append(c)
        return choices_list

    def __unicode__(self):
        return (self.text)

class Response(models.Model):
    # a response object is just a collection of questions and answers with a
    # unique interview uuid
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    survey = models.ForeignKey(Survey)
    interview_uuid = models.CharField("Interview unique identifier", max_length=36)
    user = models.ForeignKey(User,blank=True,null=True,related_name='user')

    def __unicode__(self):
        return ("response %s" % self.interview_uuid)

class AnswerBase(models.Model):
    question = models.ForeignKey(Question)
    response = models.ForeignKey(Response)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

# these type-specific answer models use a text field to allow for flexible
# field sizes depending on the actual question this answer corresponds to. any
# "required" attribute will be enforced by the form.
class AnswerText(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerRadio(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerSelect(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerSelectMultiple(AnswerBase):
    body = models.TextField(blank=True, null=True)

class AnswerInteger(AnswerBase):
    body = models.IntegerField(blank=True, null=True)

apps/communication/forms.py
from django import forms
from models import Message

class MessageForm(forms.ModelForm):

    class Meta:
        model = Message

apps/search/forms.py
from django import forms
from apps.users.models import User
from apps.search.models import Category, Favorites


class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        exclude = ['codes']


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category


class FavoritesForm(forms.ModelForm):

    class Meta:
        model = Favorites
        exclude = ['user', 'favorite_results']

templates/events/_add_activity_form.html
{% load crispy_forms_tags %}


<!-- START ROW -->



		<!-- NEW COL START -->
		<article>


            <div data-widget-custombutton="false" class="jarviswidget jarviswidget-sortable" style="" role="widget">

				<header role="heading">
					<span class="widget-icon"> <i class="fa fa-plus-circle"></i> </span>
					<h2>New Activity </h2>

				<span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span></header>

				<!-- widget div-->
				<div role="content">

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding" id="activityFormWrapper">
{#                        {% crispy form %}#}
					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>

			</article>
		<!-- END COL -->

templates/events/activitytype_list.html
{% extends 'admin_base.html' %}
{% load crispy_forms_tags %}
{% block bread_crumb %}
{% endblock bread_crumb %}

{% block extra_css %}

    <link rel="stylesheet" href="{{ STATIC_URL }}css/tablestyles.css" xmlns="http://www.w3.org/1999/html"/>

{% endblock extra_css %}

{% block content %}
<div class="row">
    <div class="col-md-12"><br/>
        <div class="col-md-12">
            <div class="col-md-8">

            </div>
            <div class="col-md-4">
                <span class="pull-right">
                    <input type="text" placeholder="Search..." name="qn" id="fid"/>
                    <input type="submit" class="btn btn-success" value="Search">
                </span>
            </div>
        </div>
        <h1 class="col-md-12"></h1>

        <!-- MAIN CONTENT -->
        <div id="content" class="col-md-12">
            <!-- widget grid -->
            <section id="widget-grid" class="">

                <!-- row -->
                <div class="row">

                    <!-- NEW WIDGET START -->
                    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                        <!-- Widget ID (each widget will need unique ID)-->
                        <div class="jarviswidget jarviswidget-color-darken" id="" data-widget-editbutton="false">
                            <header>
                                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                                <h2> Activities list </h2>

                            </header>

                            <!-- widget div-->
                            <div>

                                <!-- widget edit box -->
                                <div class="jarviswidget-editbox">
                                    <!-- This area used as dropdown edit box -->

                                </div>
                                <!-- end widget edit box -->

                                <!-- widget content -->
                                <div class="widget-body no-padding">
                                    <div class="widget-body-toolbar">
                                    </div>
                                    <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" style="text-align: center">
                                        <thead>
                                           <tr>
                                               <th>Activity Type Fullname</th>
                                               <th> ActivityType Shortname </th>
                                           </tr>
                                        </thead>
                                        <tbody>
                                            {% if activity_types %}
                                                {% for activity in activity_types %}
                                                    <tr>
                                                        <td> {{ activity.full_name }} </td>
                                                        <td> {{ activity.short_name }} </td>
                                                    </tr>
                                                {% endfor %}
                                              {% else %}
                                                    <tr >
                                                        <td> </td>
                                                        <td> </td>
                                                    </tr>
                                              {% endif %}

                                        </tbody>
                                    </table>

                                </div>
                                <!-- end widget content -->

                            </div>
                            <!-- end widget div -->

                        </div>
                        <!-- end widget -->
                    </article>
                    <!-- WIDGET END -->
                </div>
                <!-- end row -->
            </section>
            <!-- end widget grid -->
        </div>
    </div>
</div>

</div>


{% endblock content %}
{% block page_js %}


        <script src="{{ STATIC_URL }}assets/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
        <script src="{{ STATIC_URL }}assets/js/plugin/datatables/ColReorder.min.js"></script>
        <script src="{{ STATIC_URL }}assets/js/plugin/datatables/FixedColumns.min.js"></script>
        <script src="{{ STATIC_URL }}assets/js/plugin/datatables/ColVis.min.js"></script>
        <script src="{{ STATIC_URL }}assets/js/plugin/datatables/ZeroClipboard.js"></script>
        <script src="{{ STATIC_URL }}assets/js/plugin/datatables/media/js/TableTools.min.js"></script>
        <script src="{{ STATIC_URL }}assets/js/plugin/datatables/DT_bootstrap.js"></script>



    <script type="text/javascript">

        // DO NOT REMOVE : GLOBAL FUNCTIONS!

        $(document).ready(function() {


            pageSetUp();

            /*
             * BASIC
             */
            $('#dt_basic').dataTable({
                "sPaginationType" : "bootstrap_full"
            });

            /* END BASIC */

            /* Add the events etc before DataTables hides a column */
            $("#datatable_fixed_column thead input").keyup(function() {
                oTable.fnFilter(this.value, oTable.oApi._fnVisibleToColumnIndex(oTable.fnSettings(), $("thead input").index(this)));
            });

            $("#datatable_fixed_column thead input").each(function(i) {
                this.initVal = this.value;
            });
            $("#datatable_fixed_column thead input").focus(function() {
                if (this.className == "search_init") {
                    this.className = "";
                    this.value = "";
                }
            });
            $("#datatable_fixed_column thead input").blur(function(i) {
                if (this.value == "") {
                    this.className = "search_init";
                    this.value = this.initVal;
                }
            });


            var oTable = $('#datatable_fixed_column').dataTable({
                "sDom" : "<'dt-top-row'><'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
                //"sDom" : "t<'row dt-wrapper'<'col-sm-6'i><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'>>",
                "oLanguage" : {
                    "sSearch" : "Search all columns:"
                },
                "bSortCellsTop" : true
            });



            /*
             * COL ORDER
             */
            $('#datatable_col_reorder').dataTable({
                "sPaginationType" : "bootstrap",
                "sDom" : "R<'dt-top-row'Clf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
                "fnInitComplete" : function(oSettings, json) {
                    $('.ColVis_Button').addClass('btn btn-default btn-sm').html('Columns <i class="icon-arrow-down"></i>');
                }
            });

            /* END COL ORDER */

            /* TABLE TOOLS */
            $('#datatable_tabletools').dataTable({
                "sDom" : "<'dt-top-row'Tlf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
                "oTableTools" : {
                    "aButtons" : ["copy", "print", {
                        "sExtends" : "collection",
                        "sButtonText" : 'Save <span class="caret" />',
                        "aButtons" : ["csv", "xls", "pdf"]
                    }],
                    "sSwfPath" : "/static/assets/js/plugin/datatables/media/swf/copy_csv_xls_pdf.swf"
                },
                "fnInitComplete" : function(oSettings, json) {
                    $(this).closest('#dt_table_tools_wrapper').find('.DTTT.btn-group').addClass('table_tools_group').children('a.btn').each(function() {
                        $(this).addClass('btn-sm btn-default');
                    });
                }
            });

        /* END TABLE TOOLS */




        })



        </script>
<script>

    $('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});
</script>

{% endblock page_js %}

templates/events/build_form.html
{% extends "base.html" %}

{% load builder_tags %}

{% block extra_css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/formable_style.css"/> 
    <link rel="stylesheet" href="{{ STATIC_URL }}css/form_style.css"/>
{% endblock extra_css %}

{% block extra_js %}
    <script src="{{ STATIC_URL }}js/jquery-ui.js"></script>
    <script src="{{ STATIC_URL }}js/default.js"></script>
    <script src="{{ STATIC_URL }}js/helpers.js"></script>
{% endblock extra_js %}

{% block content %}

    <div>
        <h2>Survey List</h2>
    </div>
    <div class="section container row border_solid">
        {% builder %}
    </div>

{% endblock content %}

templates/events/event_details.html
{% extends 'admin_base.html' %}

{% block content %}
    <div id="content">
        <div class="row">
            <div class="col-md-12">
                <h1>Event {{ object.name }}</h1>
            </div>
        </div>
        {% with event=object active='details' %}
            {% include "events/includes/event_details_menu.html" %}
        {% endwith %}
        <div class="row">
            <div class="col-md-12">
                <h2>Subject: {{ object.subject }}</h2>
                <p>
                    <strong>Start date:</strong> {{ object.start_time|date:"Y-m-d" }}
                </p>
                <p>
                    <strong>End date:</strong> {{ object.end_time|date:"Y-m-d" }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h2>Description</h2>
                <p>
                    {{ object.description }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <tr>
                        <th>Keynote speaker</th>
                        <td>{{ object.keynote_speakers_name }}</td>
                    </tr>
                    <tr>
                        <th>Keynote speakers bio</th>
                        <td>{{ object.keynote_speakers_bio }}</td>
                    </tr>
                    <tr>
                        <th>Type</th>
                        <td>{{ object.get_is_paid_display }}</td>
                    </tr>
                    {% if object.is_paid %}
                        <tr>
                            <th>Fee</th>
                            <td>${{ object.fee }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th>Venue</th>
                        <td>{{ object.venue }}</td>
                    </tr>
                    <tr>
                        <th>
                            Registration start
                        </th>
                        <td>
                            {{ object.reg_start|date:"Y-m-d H:i" }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Registration end
                        </th>
                        <td>
                            {{ object.reg_end|date:"Y-m-d H:i" }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Registration threshold
                        </th>
                        <td>
                            {{ object.attendee_threshold }}
                        </td>
                    </tr>
                    <tr>
                        <th>Visibility</th>
                        <td>{{ object.get_visibility_display }}</td>
                    </tr>
                    <tr>
                        <th>Show schedule</th>
                        <td>{{ object.get_show_schedule_display }}</td>
                    </tr>
                    <tr>
                        <th>Require registration code:</th>
                        <td>{{ object.get_require_reg_code_display }}</td>
                    </tr>
                    {% if object.require_reg_code %}
                        <tr>
                            <th>Registration code</th>
                            <td></td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th>Active</th>
                        <td>{{ object.get_active_display }}</td>
                    </tr>
                    <tr>
                        <th>Survey</th>
                        <td>{{ object.survey }}<td>
                    </tr>
                    <tr>
                        <th>Available for feedback</th>
                        <td>{{ object.get_active_display }}</td>
                    </tr>
                    <tr>
                        <th>Social media integration</th>
                        <td>{{ object.get_social_display }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}